repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-yaml
      description: This hook checks yaml files for parseable syntax.
    - id: end-of-file-fixer
      description: Ensures that a file is either empty, or ends with one newline.
    - id: trailing-whitespace
      description: This hook trims trailing whitespace.
    - id: check-json
      description: This hook checks json files for parseable syntax
    - id: check-docstring-first
      description: Checks a common error of defining a docstring after code.
    - id:  check-merge-conflict
      description: Check for files that contain merge conflict strings.

-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    - id: black
      description:  Reformats entire files in accordance to PEP8.
      language_version: python3.9
      args: [--line-length=79]

-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      description: command-line utility for enforcing style consistency across Python projects.
